import Head from "next/head";

import Navbar from "@/components/Navbar";
import Search from "@/components/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>Your MovieApp - Discover</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="ml-4 mr-4">
        <Search />
        <div>
          <h1 className="text-white text-2xl">Hej Discover</h1>
        </div>
      </div>
    </>
  );
}
