import Head from "next/head";
import { useState, useEffect } from "react";
import MovieLists from "@/components/Movies/MovieList";
import { API_KEY, API_URL } from "../config/config";

export default function IndexPage() {
  /**
   * This function fetch the data from TMDB API
   * @param type poular or top_rated
   * @returns An array of objects
   */
  function useMovies(type: string) {
    const [movies, setMovies] = useState([]);

    async function fetchMovies() {
      const response = await fetch(
        `${API_URL}/movie/${type}?api_key=${API_KEY}&page=1`
      );
      const data = await response.json();
      setMovies(data.results);
    }

    useEffect(() => {
      fetchMovies();
    }, [fetchMovies]);

    return movies;
  }

  const popular_movies = useMovies("popular");
  const top_rated = useMovies("top_rated");

  /**
   * Fetching data: Top Ranked movies based on the data from TMDB API
   */
  {
    /** const fetching_topRatedMovies = () => {
    fetch(API_REQUEST_TOP_RATED)
      .then((response) => response.json())
      .then((data) => {
        setTopRatedMovies(data.results);
      })
      .catch((err) => {
        console.log(err);
      });
  };*/
  }

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mr-5 ml-5">
        <MovieLists
          popular_movies={popular_movies}
          topRated_movies={top_rated}
        />
      </div>
    </>
  );
}

{
  /** export const getServerSideProps: GetServerSideProps = async () => {
  const popular_response = await fetch(API_REQUEST_POPULAR);
  const topRated_respone = await fetch(API_REQUEST_TOP_RATED);

  const popular_data = await popular_response.json();
  const topRated_data = await topRated_respone.json();

  return {
    props: { popular_data, topRated_data },
  };
};
*/
}
