import Head from "next/head";
import { useState, useEffect } from "react";
import MovieLists from "@/components/Movies/Movies";

export default function IndexPage() {
  /**
   * This function fetch the data from TMDB API
   * @param type poular or top_rated
   * @returns An array of objects
   */
  function getMovies(type: string) {
    const [movies, setMovies] = useState([]);

    async function fetchMovies() {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/movie/${type}?api_key=${process.env.NEXT_PUBLIC_TMDB_API_KEY}&language=en-US`
      );
      const data = await response.json();
      setMovies(data.results);
    }

    useEffect(() => {
      fetchMovies();
    }, []);

    return movies;
  }

  const popular_movies = getMovies("popular");
  const top_rated = getMovies("top_rated");

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mr-5 ml-5">
        <MovieLists
          popular_movies={popular_movies}
          topRated_movies={top_rated}
        />
      </div>
    </>
  );
}
